### ISSUE TITLE
Follow the same convention, even for extensions

### ISSUE THREAD

**Issue by Dzoukr** [Dzoukr/Feliz.Bulma#23]
As agreed in #20, check API to don't mix conventions.

**Comment by Dzoukr** [comment]
I've went through all the extensions and they look good. The only concern is regarding colors for Tooltip extension, which has `tooltip.hasTooltipWarning` instead of `color.isWarning` (because of different class being generated).

Should we use `color.isWarning` and then on background replace it with proper class (should be in theory doable), or we keep different syntaxt because it comes from different extension?

**Comment by MangelMaxime** [comment]
We can keep the different syntax because `bulma-tooltip` doesn't generate the same "color" class.

For example, in HTML you can write:

```html
<button class="button is-danger has-tooltip-primary" data-tooltip="Tooltip Text">Primary tooltip</button>
```

Which gives you:

![image](https://user-images.githubusercontent.com/4760796/79738143-a7fd8280-82fc-11ea-9f0d-a953afc2432f.png)

In the case of `bulma-tooltip` the distinction is important because `color.isDanger` would be to control the button component and `tooltip.hasTooltipWarning` is to control the color of the tooltip.

**Comment by Dzoukr** [comment]
Makes total sense, thanks.
