### ISSUE TITLE
Check support for Femto & package validity

### ISSUE THREAD

**Issue by Dzoukr** [Dzoukr/Feliz.Bulma#3]
Please @zaid-ajaj,

this one needs your help. I'd like to have `Feliz.Bulma` package correctly setup for `Femto` - please could you check `.fsproj` file (and probably `.nuspec`) that I did it correctly? It's my first Fable package ever, so better ask for help someone skilled like you. 😉

**Comment by Zaid-Ajaj** [comment]
Sure thing! 

### Femto metadata

The included section looks fine to me. Femto even has a validation command for library authors to check that it works fine and that Femto is able to find a version that satisfies the specified version constraint:
```bash
cd src
femto --validate
```
Though I would recommend restricting the version constraint into a single major version:
```
Max(version) where 0.8.0 <= version < 0.9.0
```
Because a major version upgrade from Bulma will likely be partially incompatible with your package. So something like this maybe should work:
```xml
    <NpmDependencies>
        <NpmPackage Name="bulma" Version="&gt;= 0.8.0 &lt; 0.9.0" ResolutionStrategy="Max" />
    </NpmDependencies>
```
Again, run `femto --validate` in the directory where your project file lives to make sure Femto is able to find a correct version. 

### Include F# sources
A requirement for a F# package to be used from Fable is that you have to distribute the sources in the package itself. To do that, you must add the following into your .fsproj:
```xml
    <ItemGroup>
        <Content Include="*.fsproj; *.fs; *.js;" PackagePath="fable\" />
    </ItemGroup>
```
This line will include all the F# files and most importantly the project itself into the nuget package inside a dedicated `fable` directory which is required by Fable when compiling the package. 

### Nuspec 

Actually I haven't used `.nuspec` before 😅 I just put all the stuff inside the .fsproj file and it works like a charm, see [Fable.Recharts](https://github.com/Zaid-Ajaj/Feliz/blob/master/Feliz.Recharts/Feliz.Recharts.fsproj) for reference 

### Publishing (easily)

Here is a FAKE target I use everywhere (you probably have one too but just in case :smile:)
```fs
let publish projectPath =
    [ projectPath </> "bin"
      projectPath </> "obj" ] |> Shell.cleanDirs
    run dotnetCli "restore --no-cache" projectPath
    run dotnetCli "pack -c Release" projectPath
    let nugetKey =
        match Environment.environVarOrNone "NUGET_KEY" with
        | Some nugetKey -> nugetKey
        | None -> failwith "The Nuget API key must be set in a NUGET_KEY environmental variable"
    let nupkg =
        Directory.GetFiles(projectPath </> "bin" </> "Release")
        |> Seq.head
        |> Path.GetFullPath

    let pushCmd = sprintf "nuget push %s -s nuget.org -k %s" nupkg nugetKey
    run dotnetCli pushCmd projectPath

Target.create "PublishNuget" (fun _ -> publish "./src")
```

**Comment by Dzoukr** [comment]
Thanks for all the help! Preview version was just pushed to Nuget
