### ISSUE TITLE
Suggestion: simplify extension package names to something easier to remember? 

### ISSUE THREAD

**Issue by Zaid-Ajaj** [Dzoukr/Feliz.Bulma#6]
Hi Roman, awesome work on the extensions of Feliz.Bulma :heart: :fire: I was wondering if it is a good idea to simplify the namespacing of the libraries from `Feliz.Bulma.Extensions.{Library}` to just `Feliz.Bulma.{Library}`? This format is easier to remember when installing and is less confusing when opening the namespace in source files. Since this is very early days of Feliz.Bulma, I think a change might be doable. 

> Fable ecosystem already has a bunch of these libraries with long namespaces that confuse the users all the time, even `Fable.Core` itself! why not just `open Fable` instead of `Fable.Core` and `Fable.Core.JsInterop` where you essentially always need helpers from both (`Emit` and `jsNative`) but I digress :smile:

**Comment by Dzoukr** [comment]
Hello friend, thanks a lot! Yes, that was exactly my plan from the beginning (keep simple names), BUT then I realized that parts like QuickView, Calendar are called officialy `bulma-extensions` and also another F# wrapper for Fulma is called `Fulma.Extensions.Wikiki.Quickview` so I took the same path. I don't like it, but it seems to be sort of norm for Bulma additions. But since there is not so many of us currently using these libs (and project is still young), we can new packages, unlist old ones and have just `Feliz.Bulma.{Library}`, no problem with that. You are "founder" of Feliz style here, so you know what - it will be your call (sorry friend 😄)

**Comment by Zaid-Ajaj** [comment]
I would say go for it :smile: the Feliz norm is to make stuff as simple as possible

**Comment by Dzoukr** [comment]
I hoped you say that 😄

**Comment by Dzoukr** [comment]
I just bumped minor versions to have it "different" - all packages now listed with simplified names.

**Comment by Zaid-Ajaj** [comment]
A bumped minor version sounds great, thanks a lot :heart:

**Comment by MangelMaxime** [comment]
Hello I am coming late into the game but there was a reason why I added the name of the creator the library name.

That's because there are several "steps" library in bulma for example. Also, in npm people can publish package under their own name/scope `@scope1/bulma-library`, `@scope2/bulma-library`.

Both library have the same name, but don't have the same scope and it was reflected by using the author name.

**Comment by Dzoukr** [comment]
Hi @MangelMaxime, thanks for comment. From this issue history you already know the path it went, but what you say makes totally sense! As mentioned, your libs was kind of example to follow for me. However, it's late already to move it back so I'll keep it like that for now and we will see in future if some renaming will be necessary.
