### ISSUE TITLE
Burger not showing on mobile devices

### ISSUE THREAD

**Issue by tforkmann** [Dzoukr/Feliz.Bulma#94]
Hi there,

somehow the navbars don’t show the navbar links on mobile devices.

Any idea why?

Thanks,

Tim

**Comment by tforkmann** [comment]
![image](https://user-images.githubusercontent.com/4168951/129587444-8503b185-32f0-46aa-b7b7-23f33f337f4b.png)

**Comment by MangelMaxime** [comment]
You are probably doing something wrong because Nacara which is the website generator that power https://fable.io/ now use Feliz.Bulma and it is working.

![image](https://user-images.githubusercontent.com/4760796/129863323-068ef709-a5b1-4f14-afb9-d5fc1787be45.png)

Did you put the burger element as the last child of the brand element?

This is a requirement to have it working according to Bulma documentation:

https://bulma.io/documentation/components/navbar/#navbar-burger

> The navbar-burger is a hamburger menu that only appears on touch devices. It has to appear as the last child of navbar-brand. It has to contain three empty span tags in order to visualize the hamburger lines or the cross (when active). 

[Here is the code](https://github.com/MangelMaxime/Nacara/blob/6efa813786059d87acaae135a0752557e174e36f/src/Nacara.Layout.Standard/Source/Page.Minimal.fs#L114-L161) responsible for rendering the Navbar in Nacara:

**Comment by tforkmann** [comment]
Thanks Maxime.
Thats awesome.
Once I fixit out I will try to make a PR to the Feliz.Bulma docs page.
